#pragma config(Sensor, S3,     lightSensor,    sensorLightInactive)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	wait1Msec(50);
	while(true)	{
		nxtDisplayBigStringAt(2,40,"%d", SensorValue(lightSensor));
		wait1Msec(50);
	}
}
