#pragma config(Sensor, S1,     HTIRS2,         sensorI2CCustom)
#pragma config(Sensor, S2,     comp,           sensorI2CHiTechnicCompass)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/**
 * Code by Oscar and Jed
 * Robotics Team 2015
 */

#include "drivers/hitechnic-irseeker-v2.h"

//global variables
int fast = 50;
int slow = 10;
int lastdirection = 0;

//helper functions
int max(int x, int y)
{
	if (x > y) { return x; }
	else
	{ return y; }
}

int min(int x, int y)
{
	if (x < y) { return x; }
	else { return y; }
}

void turnLeft()
{
	motor[motorA] = fast;
	motor[motorC] = -slow;
	lastdirection = 1;
}

void turnRight()
{
	motor[motorA] = -slow;
	motor[motorC] = fast;
	lastdirection = 9;
}

void swivelLeft(int pwr)
{
	motor[motorA] = pwr;
	motor[motorC] = -pwr;
}

void swivelRight(int pwr)
{
	motor[motorA] = -pwr;
	motor[motorC] = pwr;
}

void forward()
{
	motor[motorA] = fast;
	motor[motorC] = fast;
}

void kickoff()
{
	motor[motorA] = fast;
	motor[motorC] = fast;
	wait1Msec(750);
	motor[motorA] = -fast;
	motor[motorC] = -fast;
	wait1Msec(500);
}

void turnToDirection(int current, int target)
{
	int cur = (current - target) % 360;
	if(cur > 180)
	{
		cur = 360-cur;
		swivelRight(cur);
	}
	else if (cur > 5)
	{
		swivelLeft(cur);
	}
}

//always put this task last
task main()
{
	bFloatDuringInactiveMotorPWM = true;
	kickoff();

	//set up sensor variables
	int _dirDC = 0;
  int _dirAC = 0;
	int _dirEnh, _strEnh;

	//we need our AC sensing to be at 1200Hz
  tHTIRS2DSPMode _mode = DSP_1200;

  //setup loop
  while (true)
	{
		// set the DSP to the new mode
		if (HTIRS2setDSPMode(HTIRS2, _mode))
		{
			break; // Sensor initialized
		}

		nxtDisplayCenteredTextLine(6, "Connect Sensor");
    nxtDisplayCenteredTextLine(7, "to Port S1!");
	} //setup

	//main loop
	while (true)
	{
		//int ir = SensorValue[S1];
		//int comp = SensorValue[S2];

		// Read the Enhanced direction and strength
		if (!HTIRS2readEnhanced(HTIRS2, _dirEnh, _strEnh))
    	break; // I2C read error occurred

    char str_dirEnh[15] = (char) _dirEnh;
    char str_strEnh[15] = (char) _strEnh;

    nxtDisplayCenteredTextLine(5, str_dirEnh);
    nxtDisplayCenteredTextLine(6, str_strEnh);

    //char str_ir[15];
		//char str_comp[15];

		//'print' the 'val' variable to the string (%d) 'str'.
		//sprintf(str_ir, "%d", ir);
		//sprintf(str_comp, "%d", comp);

		//nxtDisplayCenteredTextLine(5, str_ir);
		//nxtDisplayCenteredTextLine(6, str_comp);

		//turnToDirection(comp, 0);

		/*
		//when the sensor is confused
		if(ir == 0) {
			if (lastdirection == 9)
			{
				turnRight();
			}
			else if (lastdirection == 1)
			{
				turnLeft();
			}
			else
			{
				turnRight();
			}
		}
		//right
		else if (ir > 5) {
			turnRight();
		}
		//straight
		else if (ir == 5) {
			forward();
		}
		//left
		else if (ir < 5) {
			turnLeft();
		}
		*/
	} //main loop
}
